### PR TITLE
Fix the memory leak issue by closing the etcd watch client.

### LINKED ISSUE #928: Memory usage of backup-restore spiked.
**How to categorize this issue?**
/area robustness
/kind enhancement

**What would you like to be added**:
Memory optimization which can act as a safeguard in case of frequent leadership change in etcd cluster.

**Why is this needed**:

It has been observed that when etcd cluster experiences frequent leadership changes (due to n/w issue or infrastructure issue), there is a corresponding change in the backup-restore leadership as well and we have observed that this lead to spike in memory usage within backup-restore container, as shown below:

Image

Furthermore, to demonstrate that this is not a memory leak issue, please check the memory usage over a 7-day period. The memory spikes occurred only during periods when the etcd leadership was unstable.

Image

### PR DESCRIPTION
**Pull request by ishan16696**
/area backup
/kind bug

**What this PR does / why we need it**:
This PR fixes the memory leak issue by closing the etcd watch client.

**Which issue(s) this PR fixes**:
Fixes #928 

**Special notes for your reviewer**:
please check this RCA for more details: https://github.com/gardener/etcd-backup-restore/issues/928#issuecomment-3860332706

**Release note**:

```bugfix operator
Memory leak issue has been fixed by ensuring the etcd watch client is properly closed.
```

### CODE REVIEW

**Comment by ishan16696** [comment]
After the fix, I used the same [benchmark tool](https://github.com/etcd-io/etcd/tree/main/tools/benchmark) to put the dummy data in etcd (same as [RCA](https://github.com/gardener/etcd-backup-restore/issues/928#issuecomment-3860332706)) and monitored the heap size at various timestamps , the heap dump is look like this, as we can see everything is now in `KBs`.

Screenshot 2026-02-12 at 2 47 58 PM

File: pkg/snapshot/snapshotter/snapshotter.go [hunk 1]
```diff
@@ -280,7 +283,7 @@ func (ssr *Snapshotter) closeEtcdClient() {
```
Comment (anveshreddy18) [inline pkg/snapshot/snapshotter/snapshotter.go:283]: It's untouched by your PR but in this `CloseEtcdClient()` method, the condition check is not needed
Current:
```go
if ssr.watchCh != nil {
	ssr.watchCh = nil
}
```
Suggested:
```go
ssr.watchCh = nil
```

**Review by anveshreddy18 — APPROVED** [review]
Thanks for the PR @ishan16696 for catching the issue and fixing it.

Just have one nit which you can address if you're making any other changes, otherwise we can skip that part.

Other than that LGTM!.

File: pkg/snapshot/snapshotter/snapshotter.go (hunk 1 above)
Comment (ishan16696) [reply pkg/snapshot/snapshotter/snapshotter.go:283]: I have a plan to remove/refactor some of the legacy code which is not much of a use now, I will include this change in that follow-up PR which I will open after this PR if you're fine with it.

Comment (anveshreddy18) [reply pkg/snapshot/snapshotter/snapshotter.go:283]: yeah that's fine, thanks.

**Review by CaptainIRS — APPROVED** [review]
@ishan16696 thanks for the PR! I've verified that the memory leak is gone (Repro code: https://github.com/CaptainIRS/etcd-backup-restore/commit/411e01b19352f31c3e1ed47970f380cf3ff3a5ef).

| Before | After |
| --- | --- |
| image | image |
