### PR TITLE
Enhancing the scale-up detection conditions.

### LINKED ISSUE #606: [BUG] Scale-up feature fails when Etcd API calls get fail
**Describe the bug:**
It has been observed that while migrating cluster from non-HA to HA, one of etcd cluster members fails to join the cluster.
```
NAME            READY   STATUS    RESTARTS   AGE
etcd-events-0   2/2     Running   0          16h
etcd-events-1   1/2     Running   0          11h
etcd-events-2   2/2     Running   0          11h
```

```
k logs etcd-events-1 etcd 
2023-03-28 08:12:41.399729 E | rafthttp: request cluster ID mismatch (got 64e085a973abefff want becce9846230ffd3)
2023-03-28 08:12:41.400112 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[a8316960b8709b60]=64e085a973abefff, local=becce9846230ffd3)
2023-03-28 08:12:41.479401 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[e1c53a08cad26781]=64e085a973abefff, local=becce9846230ffd3)
2023-03-28 08:12:41.479598 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[e1c53a08cad26781]=64e085a973abefff, local=becce9846230ffd3)
2023-03-28 08:12:41.480089 E | rafthttp: request cluster ID mismatch (got 64e085a973abefff want becce9846230ffd3)
2023-03-28 08:12:41.481027 E | rafthttp: request cluster ID mismatch (got 64e085a973abefff want becce9846230ffd3)
2023-03-28 08:12:41.490713 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[a8316960b8709b60]=64e085a973abefff, local=becce9846230ffd3)
2023-03-28 08:12:41.505573 E | rafthttp: request cluster ID mismatch (got 64e085a973abefff want becce9846230ffd3)
2023-03-28 08:12:41.510403 E | rafthttp: request sent was ignored (cluster ID mismatch: peer[a8316960b8709b60]=64e085a973abefff, local=becce9846230ffd3)
2023-03-28 08:12:41.510509 E | rafthttp: request cluster ID mismatch (got 64e085a973abefff want becce9846230ffd3)
```

**Expected behavior:**
A new etcd cluster members should join the cluster as learner and scale-up should be successful to desired replicas.

**Root cause analysis**
During Initialization backup-restore was unable to [detect scale-up case](https://github.com/gardener/etcd-backup-restore/blob/b980beecb81485314c721500b3e51efefddc8af2/pkg/initializer/initializer.go#L54-L67) because [ProbeEtcd() call](https://github.com/gardener/etcd-backup-restore/blob/b980beecb81485314c721500b3e51efefddc8af2/pkg/member/member_control.go#L135) which internally calls [Etcd client GET()](https://github.com/gardener/etcd-backup-restore/blob/b980beecb81485314c721500b3e51efefddc8af2/pkg/miscellaneous/miscellaneous.go#L321) failed, hence `IsMemberInCluster()` return `false,err` which implies `not a scale-up case` Which lead this to backup-restore initialisation assume this as a [single node restoration in multi-node](https://github.com/gardener/etcd-backup-restore/blob/b980beecb81485314c721500b3e51efefddc8af2/pkg/initializer/initializer.go#L93-L98)(if snapstore is configured) or [restoration of single node cluster](https://github.com/gardener/etcd-backup-restore/blob/b980beecb81485314c721500b3e51efefddc8af2/pkg/initializer/initializer.go#L100-L109)(if snapstore is not configured).
It took action and initialisation returns successful but configuration provided to etcd was correctly calculated(of learner), hence it will result in failure of scale-up feature.

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID: 
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]: All

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by ishan16696**
**What this PR does / why we need it**:
This PR improves the scale-up detection conditions to avoid potential failure while migrating single node etcd to multi-node etcd cluster.

**Which issue(s) this PR fixes**:
Fixes #606 

**Special notes for your reviewer**:

**Release note**:
```improvement operator
Enhances the scale-up detection conditions to avoid potential failure while from migrating single node etcd to multi-node etcd cluster.
```

### CODE REVIEW

File: pkg/miscellaneous/miscellaneous.go [hunk 1]
```diff
@@ -564,3 +566,12 @@ func GetPrevScheduledSnapTime(nextSnapSchedule time.Time, timeWindow float64) ti
...
 }
+
+// GetBackoff returns the backoff with Factor=2
+func GetBackoff(retryPeriod time.Duration, steps int) wait.Backoff {
+	backoff := retry.DefaultBackoff
+	backoff.Duration = retryPeriod
+	backoff.Factor = 2
+	backoff.Steps = steps
+	return backoff
+}
```
Comment (seshachalam-yv) [inline pkg/miscellaneous/miscellaneous.go:577]:
```suggestion
// GetBackoff returns an exponential backoff with a factor of 2. The retry period and maximum number of steps for the backoff
// are specified by the `retryPeriod` and `steps` arguments, respectively
func GetBackoff(retryPeriod time.Duration, steps int) wait.Backoff {
	return wait.Backoff{
		Steps:    steps,
		Duration: retryPeriod,
		Factor:   2,
		Jitter:   retry.DefaultBackoff.Jitter,
	}
}
```

File: pkg/member/member_control.go [hunk 2]
```diff
@@ -299,3 +303,30 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
...
+		logger.Errorf("unable to check scale-up case :%v", err)
+	} else if state != nil && *state == miscellaneous.ClusterStateExisting {
+		return true, nil
+	}
+
+	isEtcdMemberPresent, err := m.IsMemberInCluster(ctx)
+	if err != nil {
+		return false, err
+	}
+	return !isEtcdMemberPresent, nil
```
Comment (seshachalam-yv) [inline pkg/member/member_control.go:331]:
```suggestion
	isEtcdMemberPresent, err := m.IsMemberInCluster(ctx)
	if err != nil || isEtcdMemberPresent {
		return false, err
	}
	return true, nil
```

File: pkg/member/member_control.go [hunk 3]
```diff
@@ -299,3 +303,30 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
...
+// IsScaleup determines whether a etcd cluster is getting scale-up or not.
+func IsScaleup(ctx context.Context, m Control) (bool, error) {
+	logger := logrus.New().WithField("actor", "scale-up")
+	// fetch pod name from env
+	podNS := os.Getenv("POD_NAMESPACE")
+	podName := os.Getenv("POD_NAME")
+
+	clientSet, err := miscellaneous.GetKubernetesClientSetOrError()
+	if err != nil {
+		logger.Fatalf("failed to create clientset, %v", err)
```
[the remark this answers is not in the document]
Comment (ishan16696) [reply pkg/member/member_control.go:316]: yes, it is

File: pkg/member/member_control.go [hunk 4]
```diff
@@ -299,3 +303,30 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
 
 	return miscellaneous.CheckIfLearnerPresent(learnerCtx, cli)
 }
+
+// IsScaleup determines whether a etcd cluster is getting scale-up or not.
+func IsScaleup(ctx context.Context, m Control) (bool, error) {
```
Comment (unmarshall) [inline pkg/member/member_control.go:308]: Can we do the following:

1. Rename this method to `clusterScaled`
2. Make it a method in `Control` interface instead of passing an instance of `Control` to it.
3. This method does 2 completely different things which do not belong in a single method:
    - It checks if the cluster is scaled from nonHA to HA by calling `miscellaneous.GetInitialClusterStateIfScaleup`
    - It check if the current member is already in cluster.

File: pkg/member/member_control.go [hunk 5]
```diff
@@ -299,3 +303,30 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
...
+	logger := logrus.New().WithField("actor", "scale-up")
+	// fetch pod name from env
+	podNS := os.Getenv("POD_NAMESPACE")
+	podName := os.Getenv("POD_NAME")
```
Comment (unmarshall) [inline pkg/member/member_control.go:312]: instead use `memberControl.podName`.

File: pkg/member/member_control.go [hunk 6]
```diff
@@ -299,3 +303,30 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
 
 	return miscellaneous.CheckIfLearnerPresent(learnerCtx, cli)
 }
+
+// IsScaleup determines whether a etcd cluster is getting scale-up or not.
+func IsScaleup(ctx context.Context, m Control) (bool, error) {
+	logger := logrus.New().WithField("actor", "scale-up")
+	// fetch pod name from env
+	podNS := os.Getenv("POD_NAMESPACE")
```
Comment (unmarshall) [inline pkg/member/member_control.go:311]: make `podNamespace` as an additional field in `memberControl` struct and access that.

File: pkg/member/member_control.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (unmarshall) [reply pkg/member/member_control.go:316]: I agree with Sesha, that we should not cause an exit from this method. This method should return an error. The caller of this method can decide to terminate instead. It also makes writing tests for this easier.

File: pkg/initializer/initializer.go [hunk 7]
```diff
@@ -54,11 +54,9 @@ func (e *EtcdInitializer) Initialize(mode validator.Mode, failBelowRevision int6
...
 	if miscellaneous.IsMultiNode(e.Logger.WithField("actor", "initializer")) {
 		m := member.NewMemberControl(e.Config.EtcdConnectionConfig)
-		isEtcdMemberPresent, err = m.IsMemberInCluster(ctx)
-		if !isEtcdMemberPresent && err == nil {
-			retry.OnError(retry.DefaultBackoff, func(err error) bool {
-				return err != nil
-			}, func() error {
+		isScaleup, err := member.IsScaleup(ctx, m)
+		if isScaleup && err == nil {
+			retry.OnError(retry.DefaultBackoff, errors.AnyError, func() error {
```
Comment (unmarshall) [inline pkg/initializer/initializer.go:59]: if one is sure that a cluster has been scaled up from nonHA to HA then there can be 2 approaches:
1. Infinitely attempt to add a member as learner till it succeeds
2. Try for fixed number of times and then exit causing a restart of backup-restore.
One should not proceed ahead without adding this member as a learner.

File: pkg/miscellaneous/miscellaneous.go [hunk 8]
```diff
@@ -564,3 +566,12 @@ func GetPrevScheduledSnapTime(nextSnapSchedule time.Time, timeWindow float64) ti
 		nextSnapSchedule.Location(),
 	)
 }
+
+// GetBackoff returns the backoff with Factor=2
+func GetBackoff(retryPeriod time.Duration, steps int) wait.Backoff {
```
Comment (unmarshall) [inline pkg/miscellaneous/miscellaneous.go:571]:
```suggestion
func CreateBackoff(retryPeriod time.Duration, steps int) wait.Backoff {
```

File: pkg/member/member_control.go (hunk 4 above)
Comment (ishan16696) [reply pkg/member/member_control.go:308]: > This method does 2 completely different things which do not belong in a single method:
It checks if the cluster is scaled from nonHA to HA by calling miscellaneous.GetInitialClusterStateIfScaleup
It check if the current member is already in cluster.

What makes you think that ?
IMO it `IsScaleup` does only 1 thing which it checks cluster is getting scaled-up or not using these 2 function calls:
`miscellaneous.GetInitialClusterStateIfScaleup` and `IsMemberInCluster`.

If `miscellaneous.GetInitialClusterStateIfScaleup`  says I have the annotation in sts --> surely it is scaleup case return true no need to call `IsMemberInCluster`

If `miscellaneous.GetInitialClusterStateIfScaleup` says I don't have annotation in sts  --> we still not sure about it is not being scaleup case due to bug in adding annotation to sts: https://github.com/gardener/etcd-druid/issues/557

Comment (ishan16696) [reply pkg/member/member_control.go:308]: >  Rename this method to clusterScaled

what about `IsClusterScaledup` ?

Comment (unmarshall) [reply pkg/member/member_control.go]: >what about IsClusterScaledup ?

Maybe we can use `IsClusterScaledUp`

File: pkg/member/member_control.go [hunk 9]
```diff
@@ -38,6 +42,9 @@ type Control interface {
 	// AddMemberAsLearner add a new member as a learner to the etcd cluster
 	AddMemberAsLearner(context.Context) error
 
+	// IsClusterScaledup determines whether a etcd cluster is getting scale-up or not.
+	IsClusterScaledup(context.Context, client.Client) (bool, error)
```
Comment (unmarshall) [inline pkg/member/member_control.go:46]: Scaledup are 2 words and therefore should be camel-cased. So the name should be `IsClusterScaledUp`

**Comment by ishan16696** [comment]
I have addressed reviews comments @unmarshall @seshachalam-yv . PTAL
I haven’t added unit tests. I will add, currently I'm running some tests on this PR.

File: pkg/initializer/initializer.go [hunk 10]
```diff
@@ -45,23 +45,29 @@ import (
...
-	if miscellaneous.IsMultiNode(e.Logger.WithField("actor", "initializer")) {
+	if miscellaneous.IsMultiNode(logger) {
 		m := member.NewMemberControl(e.Config.EtcdConnectionConfig)
-		isEtcdMemberPresent, err = m.IsMemberInCluster(ctx)
-		if !isEtcdMemberPresent && err == nil {
-			retry.OnError(retry.DefaultBackoff, func(err error) bool {
-				return err != nil
-			}, func() error {
+		isScaleup, err := m.IsClusterScaledup(ctx, clientSet)
+		if isScaleup && err == nil {
```
Comment (unmarshall) [inline pkg/initializer/initializer.go:64]: if a call to `IsClusterScaledup` returns an error then you currently assume that it is not a scaleup case and completely skip `AddMemberAsLeaner`.

File: pkg/member/member_control.go [hunk 11]
```diff
@@ -299,3 +314,24 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
...
+// IsClusterScaledUp determines whether a etcd cluster is getting scale-up or not and returns a boolean
+func (m *memberControl) IsClusterScaledUp(ctx context.Context) (bool, error) {
+	clientSet, err := miscellaneous.GetKubernetesClientSetOrError()
+	if err != nil {
+		m.logger.Fatalf("failed to create clientset, %v", err)
+	}
+
+	state, err := miscellaneous.GetInitialClusterStateIfScaleup(ctx, m.logger, clientSet, m.podName, m.podNamespace)
+	if err != nil {
+		m.logger.Errorf("unable to check scale-up case :%v", err)
```
Comment (aaronfern) [inline pkg/member/member_control.go:327]: This log is incorrect here, as we can print this message and then return `true` further down
Maybe we can update this message or remove this log altogether

**Review by aaronfern — CHANGES_REQUESTED** [review]

File: pkg/initializer/initializer.go (hunk 10 above)
Comment (unmarshall) [reply pkg/initializer/initializer.go:59]: >I found that if IsClusterScaledup returns an error we have to assume that it is not a scaleup case else bootstrap case 0->3 won't be possible.

There is always a possibility that an error is returned even in the case of a scale-up when calling `IsMemberInCluster` - therefore assuming that if there is an error therefore it is not a scale up case but a bootstrap (0-3) case is IMHO incorrect.

File: pkg/member/member_control.go [hunk 12]
```diff
@@ -18,12 +18,16 @@ import (
 	"go.etcd.io/etcd/etcdserver/api/v3rpc/rpctypes"
 	"go.etcd.io/etcd/etcdserver/etcdserverpb"
 	"k8s.io/client-go/util/retry"
+	//"sigs.k8s.io/controller-runtime/pkg/client"
```
Comment (aaronfern) [inline pkg/member/member_control.go:21]: Remove this commented import

File: pkg/member/member_control.go [hunk 13]
```diff
@@ -8,7 +8,7 @@ import (
 	"time"
 
 	"github.com/gardener/etcd-backup-restore/pkg/etcdutil"
-	"github.com/gardener/etcd-backup-restore/pkg/etcdutil/client"
+	etcdClient "github.com/gardener/etcd-backup-restore/pkg/etcdutil/client"
```
Comment (aaronfern) [inline pkg/member/member_control.go:11]:
```suggestion
	etcdclient "github.com/gardener/etcd-backup-restore/pkg/etcdutil/client"
```

File: pkg/member/member_control.go [hunk 14]
```diff
@@ -299,3 +314,24 @@ func (m *memberControl) IsLearnerPresent(ctx context.Context) (bool, error) {
...
+	state, err := miscellaneous.GetInitialClusterStateIfScaleup(ctx, m.logger, clientSet, m.podName, m.podNamespace)
+	if err != nil {
+		m.logger.Errorf("annotation: %v is not present: %v", miscellaneous.ScaledToMultiNodeAnnotationKey, err)
+	} else if state != nil && *state == miscellaneous.ClusterStateExisting {
+		return true, nil
+	}
+
+	isEtcdMemberPresent, err := m.IsMemberInCluster(ctx)
+	if err != nil || isEtcdMemberPresent {
+		return false, err
```
Comment (seshachalam-yv) [inline pkg/member/member_control.go:334]: We are returning an error, but it is not being handled [here](https://github.com/gardener/etcd-backup-restore/pull/608/files#diff-dc0aa715ea97877db344484988dcdffda1fc0eaeda89257be6c70e9d724721d7R58).
[`IsMemberInCluster`](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/member/member_control.go#L125-L172) is returning multiple errors. 
To ensure proper error handling, we should either handle the error or log it with a reason for why we are ignoring it.

File: pkg/initializer/initializer.go (hunk 10 above)
Comment (aaronfern) [reply pkg/initializer/initializer.go:59]: Its very difficult to distinguish between the errors here
For instance, `IsMemberInCluster` internally makes a call to `ProbeEtcd`. This could fail because we're in the bootstrapping case and etcds are not running, or due to some network issue/other issue. It's very difficult to deterministically differentiate between these two right now

File: pkg/member/member_control.go (hunk 13 above)
Comment (ishan16696) [reply pkg/member/member_control.go:11]: why not follow camel-case ?

Comment (unmarshall) [reply pkg/member/member_control.go:11]: `etcdClient` is just fine

File: pkg/member/member_control.go (hunk 14 above)
Comment (ishan16696) [reply pkg/member/member_control.go:329]: I have log the error. PTAL

**Review by aaronfern — APPROVED** [review]

File: pkg/initializer/initializer.go [hunk 15]
```diff
@@ -45,24 +45,29 @@ import (
...
+		if err != nil {
+			logger.Fatalf("failed to create clientset, %v", err)
+		}
 		m := member.NewMemberControl(e.Config.EtcdConnectionConfig)
-		isEtcdMemberPresent, err = m.IsMemberInCluster(ctx)
-		if !isEtcdMemberPresent && err == nil {
-			retry.OnError(retry.DefaultBackoff, func(err error) bool {
-				return err != nil
-			}, func() error {
+		isScaleup, err := m.IsClusterScaledUp(ctx, clientSet)
```
Comment (seshachalam-yv) [inline pkg/initializer/initializer.go:62]:
```go
		isScaleUp, err := m.IsClusterScaledUp(ctx, clientSet)
		if err != nil {
			logger.Warnf("Failed to verify cluster scale-up: %v. Proceeding with bootstrap operation.", err)
		}
		if isScaleup && err == nil {
			err = retry.OnError(retry.DefaultBackoff, errors.AnyError, func() error {
				return m.AddMemberAsLearner(ctx)
			})
			if err != nil {
				logger.Errorf("adding learner member failed: %v", err)
				return err
			}
			// Non-voting member (learner) has been successfully added, so no further restoration or validation is needed.
			return nil
		}
```
@ishan16696 
**Nit:** please check error first

Comment (seshachalam-yv) [reply pkg/initializer/initializer.go:62]: WDYT `logger.Warnf("Failed to verify cluster scale-up: %v. Proceeding with bootstrap operation.", err)`

**Review by seshachalam-yv — COMMENTED** [review]
Apart from the NIT item, LGTM.
/lgtm

File: pkg/initializer/initializer.go (hunk 15 above)
Comment (ishan16696) [reply pkg/initializer/initializer.go:62]: I will address it as a separate PR as I also need to add need unit test. I hope it make sense.
