### PR TITLE
Member Peer URL not updated when scaled to multi-node, scale identification is also not correct

### LINKED ISSUE #533: [BUG] Member Peer URL not updated when scaled to multi-node, scale identification is also not correct
**Describe the bug:**
In a single node etcd cluster today, the peer URL is not TLS enabled. When the etcd cluster is scaled from 1 to 3 then the other nodes only talk over TLS but since the first member cannot talk TLS, the other 2 members fail to join the cluster. The pods go into `CrashLoopBackOff`. To correct that we earlier merge #530, however that is not sufficient. To ensure that the TLS is now enabled for peer URL, etcd-druid will restart (implemented as delete sts + create sts) 2 times. Since the etcd configuration has already changed, the restart causes the new configuration to be available to the etcd member.  In the new configuration the cluster size is already 3. In backuprestoreserver.go the call to `UpdateMemberPeerURL` is only made when the cluster size == 1. This results in the peer URL never getting TLS enabled.

Another issue is that the way we identify if this is a scale up case is incorrect. We depend upon the following check:
```go
	if *curSts.Spec.Replicas > 1 && *curSts.Spec.Replicas > curSts.Status.UpdatedReplicas {
		return pointer.StringPtr(ClusterStateExisting), nil
	}
```
This check is not deterministic as `UpdatedReplicas` only means that the sts controller has updated all replicas to have the current revision. It does not mean they are ready. As soon as the replicas are changed from 1 to 3, UpdateReplicas also change very fast to 3, resulting in the failure of the above check, making this check timing dependent and thus non-deterministic. The state that is returned is `ClusterStateNew` which causes one of the members to start a new cluster and once it does that its clusterID does not match with the existing clusterID and it fails to join the cluster.

**Expected behavior:**

Peer URL should be TLS enabled always when etcd cluster is scaled from 1 to 3. Also the identification that this is not a bootstrap case but a scale up case should be based on time insensitive conditions.

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by unmarshall**
**What this PR does / why we need it**:

Member peer URL should always be updated. This will ensure that member peer URL is correct updated even if there was a recreation of sts and as a consequence a new configmap having a cluster size > 1 is available.
It also fixes the way we identify scale up scenario. 

**Which issue(s) this PR fixes**:
Fixes #533 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Always update member peer URL, changed the way scale-up of etcd cluster is identified.
```

### CODE REVIEW

File: pkg/server/backuprestoreserver.go [hunk 1]
```diff
@@ -224,22 +224,22 @@ func (b *BackupRestoreServer) runServer(ctx context.Context, restoreOpts *brtype
...
-			_, err = m.UpdateMemberPeerURL(ctx, cli)
-			return err
-		})
+	}
+
+	// when OriginalClusterSize = 1
+	m := member.NewMemberControl(b.config.EtcdConnectionConfig)
+	err := retry.OnError(retry.DefaultBackoff, func(err error) bool {
+		return err != nil
+	}, func() error {
```
Comment (ishan16696) [inline pkg/server/backuprestoreserver.go:233]:
```suggestion
	err := retry.OnError(retry.DefaultBackoff, AnyError, func() error {
```
Please see [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/errors/error.go#L38)

File: pkg/server/backuprestoreserver.go [hunk 2]
```diff
@@ -224,22 +224,22 @@ func (b *BackupRestoreServer) runServer(ctx context.Context, restoreOpts *brtype
...
-			cli, err := etcdutil.NewFactory(*b.config.EtcdConnectionConfig).NewCluster()
-			if err != nil {
-				return err
-			}
-			_, err = m.UpdateMemberPeerURL(ctx, cli)
-			return err
-		})
+	}
+
+	// when OriginalClusterSize = 1
```
Comment (ishan16696) [inline pkg/server/backuprestoreserver.go:229]: if we are doing the `UpdateMemberPeerURL` irrespective of clusterSize then I guess you can remove this comment.

File: pkg/server/backuprestoreserver.go [hunk 3]
```diff
@@ -224,22 +224,22 @@ func (b *BackupRestoreServer) runServer(ctx context.Context, restoreOpts *brtype
...
+	m := member.NewMemberControl(b.config.EtcdConnectionConfig)
+	err := retry.OnError(retry.DefaultBackoff, func(err error) bool {
+		return err != nil
+	}, func() error {
+		cli, err := etcdutil.NewFactory(*b.config.EtcdConnectionConfig).NewCluster()
 		if err != nil {
-			b.logger.Error("unable to update the member")
+			return err
```
Comment (ishan16696) [inline pkg/server/backuprestoreserver.go:236]: can you please log the error `fmt.Errorf("unable to create etcd cluster client ",err)` as well , so we can get to know the reason behind if we see this error log `unable to update the member`

**Review by ishan16696 — CHANGES_REQUESTED** [review]
Hi @unmarshall ,
thanks for PR.
Have you also tested the single member restoration feature with these changes ?

File: pkg/server/backuprestoreserver.go (hunk 1 above)
Comment (unmarshall) [reply pkg/server/backuprestoreserver.go:233]: Ah yes, i forgot. Changed.

File: pkg/server/backuprestoreserver.go (hunk 2 above)
Comment (unmarshall) [reply pkg/server/backuprestoreserver.go:229]: removed.

File: pkg/server/backuprestoreserver.go (hunk 3 above)
Comment (unmarshall) [reply pkg/server/backuprestoreserver.go:236]: i discussed this with Aaron. He did not want to return an error in this. Can you check with him once?

Comment (aaronfern) [reply pkg/server/backuprestoreserver.go:233]: This line in inside a `retry.OnError` function, so imo it's okay if it is not logged here as it will be anyway logged in line [239](https://github.com/gardener/etcd-backup-restore/pull/534/files#diff-df6f7abbd9069d0a874a18b5717de5b0fcd68dac32184fdcdc2a26019be2296fR239)
Having said that, can you please update [line 239](https://github.com/gardener/etcd-backup-restore/pull/534/files#diff-df6f7abbd9069d0a874a18b5717de5b0fcd68dac32184fdcdc2a26019be2296fR239) to print the error along with the log?

File: pkg/miscellaneous/miscellaneous.go [hunk 4]
```diff
@@ -417,24 +419,27 @@ func IsBackupBucketEmpty(snapStoreConfig *brtypes.SnapstoreConfig, logger *logru
...
-		return ClusterStateNew
+	if err != nil {
+		logger.Warn("error fetching etcd sts ", err)
+		return nil, err
 	}
 
-	//TODO: achieve this without an sts?
-	if *curSts.Spec.Replicas > 1 && *curSts.Spec.Replicas > curSts.Status.UpdatedReplicas {
-		return ClusterStateExisting
+	if metav1.HasAnnotation(curSts.ObjectMeta, "gardener.cloud/scaled-to-multi-node") {
```
Comment (aaronfern) [inline pkg/miscellaneous/miscellaneous.go:434]: Please define a constant for this annotation and use that constant in the check here

File: pkg/server/backuprestoreserver.go [hunk 5]
```diff
@@ -224,22 +224,19 @@ func (b *BackupRestoreServer) runServer(ctx context.Context, restoreOpts *brtype
...
 		}
+		_, err = m.UpdateMemberPeerURL(ctx, cli)
+		return err
+	})
+	if err != nil {
+		b.logger.Error("unable to update the member")
```
Comment (aaronfern) [inline pkg/server/backuprestoreserver.go:239]:
```suggestion
		b.logger.Error("unable to update the member: ", err)
```

**Review by aaronfern — CHANGES_REQUESTED** [review]
Thanks for the PR @unmarshall!
Few suggestions from me, looks good otherwise

File: pkg/server/backuprestoreserver.go (hunk 3 above)
Comment (unmarshall) [reply pkg/server/backuprestoreserver.go:233]: done

File: pkg/miscellaneous/miscellaneous.go (hunk 4 above)
Comment (unmarshall) [reply pkg/miscellaneous/miscellaneous.go:434]: done

**Comment by unmarshall** [comment]
> Have you also tested the single member restoration feature with these changes ?
@ishan16696  no i have not tested that explicitly. Let us sync up tomorrow and test it out.

File: pkg/server/backuprestoreserver.go [hunk 6]
```diff
@@ -224,24 +210,28 @@ func (b *BackupRestoreServer) runServer(ctx context.Context, restoreOpts *brtype
...
-		m := member.NewMemberControl(b.config.EtcdConnectionConfig)
-		err := retry.OnError(retry.DefaultBackoff, func(err error) bool {
-			return err != nil
-		}, func() error {
-			cli, err := etcdutil.NewFactory(*b.config.EtcdConnectionConfig).NewCluster()
-			if err != nil {
-				return err
-			}
-			_, err = m.UpdateMemberPeerURL(ctx, cli)
+	}
```
Comment (abdasgupta) [inline pkg/server/backuprestoreserver.go:213]: We don't need this block of promoting member. We are already promoting member downwards. Can we remove it?

**Review by abdasgupta — CHANGES_REQUESTED** [review]

File: pkg/server/backuprestoreserver.go (hunk 6 above)
Comment (unmarshall) [reply pkg/server/backuprestoreserver.go:213]: Yes this was removed in this PR. Maybe i did not understand your suggestion. If you view the file you will see that this block was removed. Now we always want to promote a member irrespective of cluster size.

**Review by ishan16696 — CHANGES_REQUESTED** [review]
I have tested the PR for single member restoration. It is working fine.
Just a one nitpicks.

File: pkg/server/backuprestoreserver.go [hunk 7]
```diff
@@ -62,7 +62,7 @@ var (
 	// runServerWithSnapshotter indicates whether to start server with or without snapshotter.
 	runServerWithSnapshotter bool = true
 	retryTimeout                  = 5 * time.Second
-	peerURLTLSEnabled        bool
+	//peerURLTLSEnabled        bool
```
[the remark this answers is not in the document]
Comment (unmarshall) [reply pkg/server/backuprestoreserver.go]: done

File: pkg/server/backuprestoreserver.go (hunk 6 above)
Comment (ishan16696) [reply pkg/server/backuprestoreserver.go:212]: I think what @abdasgupta is saying that we are promoting the learner in leader-election as well. check [here](https://github.com/gardener/etcd-backup-restore/blob/master/pkg/leaderelection/leaderelection.go#L153-L157).
@aaronfern can we remove this from here or may be @abdasgupta you can address this in your PR ?

Comment (abdasgupta) [reply pkg/server/backuprestoreserver.go:212]: Better if you remove PromoteMember from here. But keep the UpdateMemberPeerURL

**Review by abdasgupta — APPROVED** [review]

**Review by ishan16696 — APPROVED** [review]

**Review by aaronfern — APPROVED** [review]
/lgtm
