### PR TITLE
Enhancement: Implement Chunk Deletion for Multi-part Uploaded Files on GCP and Openstack Cloud Providers

### LINKED ISSUE #268: [BUG] Individual chunks of multipart upload are still present after upload has been completed
**Describe the bug:**
The current chunked backup upload implementation relies on the storage provider to clean up the individual chunks after the upload has been completed. S3 does this [automatically](https://docs.aws.amazon.com/AmazonS3/latest/dev/mpuoverview.html). But GCS [doesn't](https://cloud.google.com/storage/docs/composite-objects#composing). This means that the chunks remain in GCS and eat up space. This might be true in other storage providers.

Credit: @majst01

**Expected behavior:**
Individual chunks should be deleted after the chunked upload has been completed either by the storage provider or by `etcd-backup-restore`.

**How To Reproduce (as minimally and precisely as possible):**
Use GCS as the storage provider.

**Logs:**

**Screenshots (if applicable):**
image

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-backup-restore version/commit ID:
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by anveshreddy18**
**What this PR does / why we need it**:

After the snapshots are uploaded as multiple parts (Chunks) to cloud storage buckets, chunks are not auto-deleted on a few cloud providers. Out of the providers we use, GCP & OpenStack does not delete the chunks after forming composite object. These chunks take up space equal to its corresponding composite object. With this PR, storage occupancy & cost of the bucket can be reduced to half.

Added functionality in GC to delete chunks

**Which issue(s) this PR fixes**:
Fixes #268

**Special notes for your reviewer**:

**Release note**:

```improvement operator
Enhanced Garbage Collector to garbage collect the chunks for cloud providers like GCP and OpenStack which does not automatically delete snapshot chunks after the formation of a composite object.
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @anveshreddy18 for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 1]
```diff
@@ -193,24 +192,28 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
 	return snapStreamIndexList
 }
 
-// garbageCollectChunks deletes the chunks in the store from snaplist starting at index low (inclusive) till high (exclusive).
-func garbageCollectChunks(store brtypes.SnapStore, snapList brtypes.SnapList, low, high int) {
-	for index := low; index < high; index++ {
+// garbageCollectChunks deletes the chunks in the store from snaplist.
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:195]: Shall we improvise the comment something like below
WDYT ? 
```suggestion
// garbageCollectChunks goes through the snapList and deletes any chunks.
// It returns a list of non-chunk snapshots, preserving the original order.
```

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 2]
```diff
@@ -193,24 +192,28 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
+func garbageCollectChunks(store brtypes.SnapStore, snapList brtypes.SnapList) brtypes.SnapList {
+	var snapListWithoutChunks brtypes.SnapList
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:197]:
```suggestion
	var nonChunkSnapList brtypes.SnapList
```

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 3]
```diff
@@ -193,24 +192,28 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
+	for index := 0; index < len(snapList); index++ {
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:198]:
```suggestion
	for _, snap := range snapList {
```
Can we use `range`instead of `index`

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 4]
```diff
@@ -193,24 +192,28 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
 		snap := snapList[index]
-		// Only delete chunk snapshots of kind Full
-		if snap.Kind != brtypes.SnapshotKindFull || !snap.IsChunk {
+		// If not chunk, add to list and continue
+		if !snap.IsChunk {
+			snapListWithoutChunks = append(snapListWithoutChunks, snap)
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:202]:
```suggestion
			nonChunkSnapList = append(nonChunkSnapList, snap)
```

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 5]
```diff
@@ -193,24 +192,28 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
 		if err := store.Delete(*snap); err != nil {
-			logrus.Warnf("GC: Failed to delete snapshot %s: %v", snapPath, err)
+			logrus.Warnf("GC: Failed to delete chunk %s: %v", snapPath, err)
 			metrics.SnapshotterOperationFailure.With(prometheus.Labels{metrics.LabelError: err.Error()}).Inc()
 			metrics.GCSnapshotCounter.With(prometheus.Labels{metrics.LabelKind: brtypes.SnapshotKindChunk, metrics.LabelSucceeded: metrics.ValueSucceededFalse}).Inc()
 			continue
 		}
 		metrics.GCSnapshotCounter.With(prometheus.Labels{metrics.LabelKind: brtypes.SnapshotKindChunk, metrics.LabelSucceeded: metrics.ValueSucceededTrue}).Inc()
 	}
+	return snapListWithoutChunks
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:216]:
```suggestion
	return nonChunkSnapList
```

File: pkg/snapstore/gcs_snapstore.go [hunk 6]
```diff
@@ -167,6 +167,18 @@ func (s *GCSSnapStore) Save(snap brtypes.Snapshot, rc io.ReadCloser) error {
...
+	// To be done once the composite object is successfully uploaded.
+	logrus.Infof("Started deleting the chunk objects from bucket")
+	for partNumber := int64(1); partNumber <= noOfChunks; partNumber++ {
+		name := path.Join(prefix, snap.SnapDir, snap.SnapName, fmt.Sprintf("%010d", partNumber))
+		obj := bh.Object(name)
+		err := obj.Delete(context.TODO())
+		if err != nil {
+			return fmt.Errorf("failed to delete chunk with id: %d ", partNumber)
+		}
+	}
```
Comment (seshachalam-yv) [inline pkg/snapstore/gcs_snapstore.go:181]: - Encapsulate the chunk deletion logic into a dedicated function to improve code clarity, readability, and reusability.
- Utilize a context with a timeout when deleting chunks to prevent operations from hanging indefinitely.
- Accumulate errors encountered during chunk deletions instead of returning immediately upon the first error.
- Return all accumulated errors together after all deletion attempts, ensuring thorough cleanup and detailed feedback on the operation’s results.

**Review by seshachalam-yv — CHANGES_REQUESTED** [review]

File: pkg/snapstore/gcs_snapstore.go [hunk 7]
```diff
@@ -167,6 +167,24 @@ func (s *GCSSnapStore) Save(snap brtypes.Snapshot, rc io.ReadCloser) error {
...
+
+	// Log the errors occured while deleting the chunks
+	for _, errLog := range errList {
+		fmt.Println(errLog)
+	}
+
+	if len(errList) > 0 {
+		return fmt.Errorf("failed deleting chunks in GCS for snapshot: %v", snap.SnapName)
+	}
+	logrus.Infof("Successfully deleted %d chunks from GCS bucket", noOfChunks)
```
Comment (seshachalam-yv) [inline pkg/snapstore/gcs_snapstore.go:187]: Currently, we're deleting chunks one by one, which slows down the deletion process. We should consider using a parallel deletion approach, similar to our upload method with `collectChunkUploadError`, to speed things up.

**Review by seshachalam-yv — CHANGES_REQUESTED** [review]

File: pkg/snapstore/gcs_snapstore.go (hunk 7 above)
Comment (anveshreddy18) [reply pkg/snapstore/gcs_snapstore.go]: Thanks sesha. Addressed the review comment in latest commit. Closing this

**Comment by seshachalam-yv** [comment]
After reviewing the code, I've noticed that immediate chunk deletion introduces complexity, especially when dealing with a large number of chunks. This requires spawning numerous goroutines to prevent blocking the `snapshot.Save()` function. However, this approach significantly increases the complexity of managing retry mechanisms and the lifecycle of goroutines dedicated to chunk deletions.

Let the garbage collector (GC) handle chunk deletion exclusively. This change could streamline the process by reducing the operational complexity and improving the maintainability of our code.

WDYT @anveshreddy18, @ishan16696, @shreyas-s-rao ?

File: pkg/snapstore/swift_snapstore.go [hunk 8]
```diff
@@ -440,6 +447,61 @@ func (s *SwiftSnapStore) chunkUploader(wg *sync.WaitGroup, stopCh <-chan struct{
 	}
 }
 
+// chunkRemover is a GoRoutine to perform the chunk deletion operation
```
Comment (ishan16696) [inline pkg/snapstore/swift_snapstore.go:450]:
```suggestion
// chunkRemover perform the chunk deletion operation
```

File: pkg/snapstore/swift_snapstore.go [hunk 9]
```diff
@@ -396,6 +397,12 @@ func (s *SwiftSnapStore) Save(snap brtypes.Snapshot, rc io.ReadCloser) error {
 		return fmt.Errorf("failed uploading manifest for snapshot with error: %v", res.Err)
 	}
 	logrus.Info("Manifest object uploaded successfully.")
+
+	chunkDeleteCtx, chunkDeleteCancel := context.WithTimeout(context.TODO(), chunkUploadTimeout)
```
Comment (ishan16696) [inline pkg/snapstore/swift_snapstore.go:401]:
```suggestion
	chunkDeleteCtx, chunkDeleteCancel := context.WithTimeout(context.Background(), chunkUploadTimeout)
```
It's better to use `context.Background()` if no parent context is passed to the function. Similar for other places where `context.TODO()` is used

File: pkg/snapstore/swift_snapstore.go [hunk 10]
```diff
@@ -440,6 +447,61 @@ func (s *SwiftSnapStore) chunkUploader(wg *sync.WaitGroup, stopCh <-chan struct{
...
+			res := objects.Delete(s.client, s.bucket, chunk.chunkName, deleteOpts)
+			deleteResCh <- chunkDeleteResult{
+				err:         res.Err,
+				deleteChunk: &chunk,
+			}
+		}
+	}
+}
+
+// deleteChunks spans multiple GoRoutines to delete chunks from the Openstack Swift store in parallel
```
Comment (ishan16696) [inline pkg/snapstore/swift_snapstore.go:472]:
```suggestion
// deleteChunks spawns multiple GoRoutines to delete chunks in parallel from the Openstack Swift snapStore 
```

**Comment by ishan16696** [comment]
> After reviewing the code, I've noticed that immediate chunk deletion introduces complexity, especially when dealing with a large number of chunks. This requires spawning numerous goroutines to prevent blocking the snapshot.Save() function. However, this approach significantly increases the complexity of managing retry mechanisms and the lifecycle of goroutines dedicated to chunk deletions.

Let the garbage collector (GC) handle chunk deletion exclusively. This change could streamline the process by reducing the operational complexity and improving the maintainability of our code.

yes, seems complex to me as well. I will also vote for `garbage collector (GC) handle chunk deletion`.

**Comment by anveshreddy18** [comment]
Context:: After discussing the need for immediate chunk deletion, it is decided that we don't need to make it complex and also functionality wise, it should be done by GC so letting GC delete the chunks. 

My recent commit has changes according to that. Please take a look once @seshachalam-yv @ishan16696

File: pkg/snapstore/gcs_snapstore.go [hunk 11]
```diff
@@ -215,6 +223,62 @@ func (s *GCSSnapStore) componentUploader(wg *sync.WaitGroup, stopCh <-chan struc
...
+			chunkName:  name,
+			partNumber: partNumber,
+		}
+		chunkDeleteCh <- newDeleteChunk
+	}
+
+	chunkDeleteErr := collectChunkDeleteError(chunkDeleteCh, deleteResCh, deleteCancelCh, noOfChunks)
+	if chunkDeleteErr != nil {
+		logrus.Errorf("Chunk deletion unsuccessful for few chunks, will be taken care of by GC")
+	}
```
[the remark this answers is not in the document]
Comment (anveshreddy18) [reply pkg/snapstore/gcs_snapstore.go]: Marking these as resolved as the code is outdated.

**Comment by ishan16696** [comment]
> Context:: After discussing the need for immediate chunk deletion, it is decided that we don't need to make it complex and also functionality wise, it should be done by GC so letting GC delete the chunks.

Thanks @anveshreddy18 for changes, please change the release note accordingly to reflect the functionality.

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 12]
```diff
@@ -193,24 +196,33 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
 
-// garbageCollectChunks deletes the chunks in the store from snaplist starting at index low (inclusive) till high (exclusive).
-func garbageCollectChunks(store brtypes.SnapStore, snapList brtypes.SnapList, low, high int) {
-	for index := low; index < high; index++ {
-		snap := snapList[index]
-		// Only delete chunk snapshots of kind Full
-		if snap.Kind != brtypes.SnapshotKindFull || !snap.IsChunk {
+// garbageCollectChunks goes through the snapList and deletes any chunks
+// Returns a list of non-chunk snapshots, preserving the original order
+func garbageCollectChunks(store brtypes.SnapStore, snapList brtypes.SnapList, prevSnapshot *brtypes.Snapshot) (int, brtypes.SnapList) {
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:201]: Could you please refactor the `garbageCollectChunks` function to be a method of the `Snapshotter` struct, similar to how `GarbageCollectDeltaSnapshots` is implemented? This change would allow it to directly access the `logger` and `store` attributes, eliminating the need to pass these as arguments.

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 13]
```diff
@@ -193,24 +196,33 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
-		}
-		snapPath := path.Join(snap.SnapDir, snap.SnapName)
-		logrus.Infof("GC: Deleting chunk for old full snapshot: %s", snapPath)
-		if err := store.Delete(*snap); err != nil {
-			logrus.Warnf("GC: Failed to delete snapshot %s: %v", snapPath, err)
-			metrics.SnapshotterOperationFailure.With(prometheus.Labels{metrics.LabelError: err.Error()}).Inc()
-			metrics.GCSnapshotCounter.With(prometheus.Labels{metrics.LabelKind: brtypes.SnapshotKindChunk, metrics.LabelSucceeded: metrics.ValueSucceededFalse}).Inc()
+		} else if snap.StartRevision > prevSnapshot.LastRevision {
 			continue
+		} else {
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:211]: Could you consider simplifying the conditions for better readability 

``` go
		if !snapshot.IsChunk {
                         // ...
			continue
		}


		if snapshot.StartRevision > prevSnapshot.LastRevision {
			continue
		}
		
		// ...
		// ...
```

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 14]
```diff
@@ -193,24 +196,33 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
+			// delete the chunk object
+			snapPath := path.Join(snap.SnapDir, snap.SnapName)
+			logrus.Infof("GC: Deleting chunk for old snapshot: %s", snapPath)
+			if err := store.Delete(*snap); err != nil {
+				logrus.Warnf("GC: Failed to delete chunk %s: %v", snapPath, err)
```
Comment (seshachalam-yv) [inline pkg/snapshot/snapshotter/garbagecollector.go:216]: Use the logger from `Snapshotter`

**Review by seshachalam-yv — CHANGES_REQUESTED** [review]

File: pkg/snapshot/snapshotter/garbagecollector.go (hunk 12 above)
Comment (anveshreddy18) [reply pkg/snapshot/snapshotter/garbagecollector.go:201]: Yeah definitely. Thanks Sesha for the suggestions

File: pkg/snapshot/snapshotter/garbagecollector.go [hunk 15]
```diff
@@ -193,24 +195,35 @@ func getSnapStreamIndexList(snapList brtypes.SnapList) []int {
...
-// garbageCollectChunks deletes the chunks in the store from snaplist starting at index low (inclusive) till high (exclusive).
-func garbageCollectChunks(store brtypes.SnapStore, snapList brtypes.SnapList, low, high int) {
-	for index := low; index < high; index++ {
-		snap := snapList[index]
-		// Only delete chunk snapshots of kind Full
-		if snap.Kind != brtypes.SnapshotKindFull || !snap.IsChunk {
+// GarbageCollectChunks removes obsolete chunks based on the latest recorded snapshot.
+// It eliminates chunks associated with snapshots that have already been uploaded.
+// Additionally, it avoids deleting chunks linked to snapshots currently being uploaded to prevent the garbage collector from removing chunks before the composite is formed.
+func (ssr *Snapshotter) GarbageCollectChunks(snapList brtypes.SnapList) (int, brtypes.SnapList) {
```
Comment (ishan16696) [inline pkg/snapshot/snapshotter/garbagecollector.go:201]: Why you are making this func as public ?

Comment (anveshreddy18) [reply pkg/snapshot/snapshotter/garbagecollector.go:201]: That was a requirement for the unit tests. I was writing unit tests so I had to make it accessible for other packages. For eg, GC is in snapshotter pkg but unit tests for GC functions are in snapshotter_test pkg, so to use the func for unit tests, I had to make those it public. 

All other funcs are also public for the exact same reason. So I changed this func also as it was necessary.
