### PR TITLE
Don't fail the Ownercheck when DNS resolve lookup fails.

### LINKED ISSUE #437: [Feature] OwnerCheck shouldn't fails the ReadinessProbe right away.
**Feature (What you would like to be added):**
Currently,  when the [OwnerCheck](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/common/ownerchecker.go#L43) fails it sets the [HTTP status to StatusServiceUnavailable](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/server/backuprestoreserver.go#L267) right away which can leads to outages as it fails the `ReadinessProbe` of etcd. So, we need to provide some delay or backoff-mechanism such that OwnerCheck shouldn't fails the ReadinessProbe of `etcd` right away.

**Motivation (Why is this needed?):**
OwnerCheck shouldn't fails the ReadinessProbe until we are sure that OwnerCheck has failed because OwnerCheck can also fails due to DNS throttling or network delays.

**Approach/Hint to the implement solution (optional):**

### PR DESCRIPTION
**Pull request by ishan16696**
**What this PR does / why we need it**:
Don't set the [HTTP  handler status to StatusServiceUnavailable](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/server/backuprestoreserver.go#L267) when the ownercheck's [DNS resolve lookup](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/common/ownerchecker.go#L59) fails.
Set the [HTTP  handler status to StatusServiceUnavailable](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/server/backuprestoreserver.go#L267) only when  [OwnerCheck](https://github.com/gardener/etcd-backup-restore/blob/03920151cfeeb50d6e8a35c7de2aa1f7c6670625/pkg/common/ownerchecker.go#L43) confirms that the current ownership has changed.

**Which issue(s) this PR fixes**:
Fixes #437 

**Special notes for your reviewer**:

**Release note**:
```improvement operator
NONE
```

cc @plkokanov

### CODE REVIEW

File: pkg/server/backuprestoreserver.go [hunk 1]
```diff
@@ -275,17 +275,26 @@ func (b *BackupRestoreServer) runEtcdProbeLoopWithSnapshotter(ctx context.Contex
...
 		}
 
-		// set server's healthz endpoint status to OK so that
-		// etcd is marked as ready to serve traffic
-		handler.SetStatus(http.StatusOK)
-
 		if runServerWithSnapshotter {
 			if b.ownerChecker != nil {
 				// Check if the actual owner ID matches the expected one
 				// If the check fails or returns false, take a final full snapshot if needed
```
Comment (plkokanov) [inline pkg/server/backuprestoreserver.go:281]: Adapt this comment to the new changes appropriately.

File: pkg/server/backuprestoreserver.go [hunk 2]
```diff
@@ -275,17 +275,26 @@ func (b *BackupRestoreServer) runEtcdProbeLoopWithSnapshotter(ctx context.Contex
...
+
+					// Wait for the configured interval before making another attempt
+					b.logger.Infof("Waiting for %s...", b.config.OwnerCheckConfig.OwnerCheckInterval.Duration)
+					select {
+					case <-ctx.Done():
+						b.logger.Info("Shutting down...")
+						return
+					case <-time.After(b.config.OwnerCheckConfig.OwnerCheckInterval.Duration):
+					}
+					continue
```
Comment (plkokanov) [inline pkg/server/backuprestoreserver.go:295]: Why do we need this retry logic here? If the etcd gets restarted while there are connectivity problems to the DNS, it will not be able to start again.

**Review by plkokanov — CHANGES_REQUESTED** [review]

File: pkg/server/backuprestoreserver.go (hunk 2 above)
Comment (ishan16696) [reply pkg/server/backuprestoreserver.go:295]: why etcd will not be able to start again?

File: pkg/server/backuprestoreserver.go (hunk 1 above)
Comment (ishan16696) [reply pkg/server/backuprestoreserver.go:281]: I didn’t get it ?

Comment (ishan16696) [reply pkg/server/backuprestoreserver.go:281]: just wanted to set the readinessProbe only after `ownercheck` succeed/fail . Previously I missed to test this [PR](https://github.com/gardener/etcd-backup-restore/pull/411) with ownercheck.

Comment (plkokanov) [reply pkg/server/backuprestoreserver.go:281]: I guess I wasn't very clear since my comment is on a line that wasn't changed in the PR. I meant that 
```suggestion
				// If the check returns false, take a final full snapshot if needed. If the check returns an error continue with normal operation.
```

File: pkg/server/backuprestoreserver.go (hunk 2 above)
Comment (plkokanov) [reply pkg/server/backuprestoreserver.go:295]: I meant the following scenario:
1. There are some errors with DNS on the landscape. 
2. For some other reason etcd-backup-restore is restarted
3. When etcd-backup-restore starts it will try to do the owner check on line 283
4. If the owner check returns an error, the select/case will block until the `b.config.OwnerCheckConfig.OwnerCheckInterval.Duration` has expired
5. Once the time expires, the loop is repeated, if there is yet again an error from the owner check then the select/case will block the loop again. 
6. Steps 4 and 5 will be repeated until the DNS errors are resolved and therefore `handler.SetStatus(http.StatusOK)` is not called and etcd-backup-restore does not become ready and snapshotter is not started

Comment (ishan16696) [reply pkg/server/backuprestoreserver.go:295]: make sense.

**Review by plkokanov — APPROVED** [review]
/lgtm atleast form my side, seems like the snapshotter unit tests are failing for some reaosn though.

**Review by aaronfern — APPROVED** [review]
/lgtm
