### PR TITLE
Initialize Prometheus metrics before exposing

### LINKED ISSUE #167: [BUG] Some metrics return no values
**Describe the bug:**
Prometheus [best practices](https://www.robustperception.io/existential-issues-with-metrics)  is to avoid missing metrics whenever possible. Some of the metrics that are exposed by the sidecar return no values if no event has occurred that would generate a value for this metric. These metrics should be initialized to 0 to prevent this problem. Some offending metrics are:
* `etcdbr_snapshot_gc_total`
* `etcdbr_restoration_duration_seconds_*`
* `etcdbr_defragmentation_duration_seconds_*`

**Expected behaviour:**
There should be no "missing metrics." All metrics should be initialized to 0 (or another value if 0 doesn't make sense).

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>

**What this PR does / why we need it**:
This PR initializes all Prometheus metrics to their respective zero-values before exposing them.

**Which issue(s) this PR fixes**:
Fixes #167 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
NONE
```

### CODE REVIEW

File: pkg/metrics/metrics.go [hunk 1]
```diff
@@ -105,7 +118,128 @@ var (
...
+	for i := 0; i < len(a); i++ {
+		for j := 0; j < len(b); j++ {
+			output = append(output, append(a[i], b[j]...))
+		}
+	}
+	return output
+}
+
+// wrapInSlice is a helper function to wrap a slice of strings within
+// a slice of slices of strings
```
Comment (swapnilgm) [inline pkg/metrics/metrics.go]:
```suggestion
// a slice of slices of strings
// e.g. [a,b,c] -> [[a],[b],[c]]
```

File: pkg/metrics/metrics.go [hunk 2]
```diff
@@ -105,7 +118,128 @@ var (
...
+		return [][]string{}
+	} else if len(valuesList) == 1 {
+		return wrapInSlice(valuesList[0])
+	}
+
+	return cartesianProduct(wrapInSlice(valuesList[0]), getCombinations(valuesList[1:]))
+}
+
+// cartesianProduct combines two slices of slice of strings while also
+// combining the sub-slices of strings into a single string
```
Comment (swapnilgm) [inline pkg/metrics/metrics.go]:
```suggestion
// combining the sub-slices of strings into a single string
// e.g.
// a => [[p,q],[r,s]]
// b => [[1,2],[3,4]]
//  Output <= [[p,q,1,2],[p,q,3,4],[r,s,1,2],[r,s,3,4]]

File: pkg/metrics/metrics.go (hunk 1 above)
Comment (shreyas-s-rao) [reply pkg/metrics/metrics.go]: Done.

File: pkg/metrics/metrics.go (hunk 2 above)
Comment (shreyas-s-rao) [reply pkg/metrics/metrics.go]: Done.

**Comment by shreyas-s-rao** [comment]
@swapnilgm Thanks for the review. I have addressed the changes and also added tests for the helper functions. PTAL.
